build:
  image: xena/nim:0.14.2
  commands:
    - nimble refresh
    - yes | nimble install
    - cd client/nim
    - sh ./test.sh

deploy:
  git_push:
    branch: master
    remote: git@github.com:Xe/PonyAPI.git

  ssh:
    host: greedo.xeserv.us
    user: xena
    port: 22
    commands:
      - cd ~/code/ponyapi
      - docker-compose build
      - docker-compose up -d
