build:
  image: xena/nim:0.14.2
  commands:
    - nimble refresh
    - yes | nimble install
    - cd client/nim
    - bash ./test.sh

deploy:
  git_push:
    branch: master
    remote: git@github.com:Xe/PonyAPI.git
